version: "3.4"
services:
  redis:
    restart: always
    image: redis:latest

  gateway:
    restart: always
    depends_on:
      - redis
    build:
      context: ./
      target: cg_gateway
    ports:
      - "8912:8912"
  game:
    restart: always
    depends_on:
      - redis
    build:
      context: ./
      target: cg_game
    volumes:
      - ./data:/data
